"""Detection signals for Provenance Guard.

Signal 1 (this milestone): LLM classification via Groq. Captures holistic
semantic/stylistic coherence — the "fingerprint" of AI-generated prose.

Signal 2 (stylometric heuristics) is added in Milestone 4.
"""

import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_MODEL = "llama-3.3-70b-versatile"
_client = None


def _get_client():
    """Lazily construct the Groq client so importing this module never fails
    just because the key isn't loaded yet."""
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


_SYSTEM_PROMPT = (
    "You are an AI-content forensics assistant. Given a piece of text, assess how "
    "likely it was generated by an AI language model rather than written by a human. "
    "Look for AI fingerprints: hedging boilerplate, even rhythm, uniform sentence "
    "structure, topic-sentence-then-elaboration patterns, and an absence of lived, "
    "specific detail. Human writing tends to be 'burstier', more idiosyncratic, and "
    "more concretely specific.\n\n"
    "Respond ONLY with a JSON object of the form:\n"
    '{"ai_likelihood": <float 0.0-1.0>, "rationale": "<one sentence>"}\n'
    "where 1.0 means almost certainly AI-generated and 0.0 means almost certainly "
    "human-written. Do not include any other text."
)


def llm_signal(text):
    """Return {'llm_score': float in [0,1], 'rationale': str}.

    llm_score is the model's estimated probability that the text is AI-generated.
    On any failure we return a neutral 0.5 with an error note rather than raising,
    so a single bad API call never takes down a submission.
    """
    try:
        resp = _get_client().chat.completions.create(
            model=_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            response_format={"type": "json_object"},
            temperature=0.0,
        )
        data = json.loads(resp.choices[0].message.content)
        score = float(data.get("ai_likelihood"))
        score = max(0.0, min(1.0, score))  # clamp defensively
        rationale = str(data.get("rationale", "")).strip()
        return {"llm_score": score, "rationale": rationale}
    except Exception as exc:  # noqa: BLE001 — degrade gracefully, don't crash /submit
        return {
            "llm_score": 0.5,
            "rationale": f"LLM signal unavailable, defaulting to neutral ({exc}).",
        }


if __name__ == "__main__":
    # Independent test harness — run `python signals.py` to inspect the signal
    # directly before wiring it into the endpoint (per the M3 AI Tool Plan).
    samples = {
        "clearly_ai": (
            "Artificial intelligence represents a transformative paradigm shift in "
            "modern society. It is important to note that while the benefits of AI "
            "are numerous, it is equally essential to consider the ethical "
            "implications. Furthermore, stakeholders across various sectors must "
            "collaborate to ensure responsible deployment."
        ),
        "clearly_human": (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in "
            "it and i was thirsty for like three hours after."
        ),
    }
    for name, sample in samples.items():
        result = llm_signal(sample)
        print(f"{name:>14}: {result}")
